package master

func migrateV5SQL() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS tunnels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  server_id TEXT NOT NULL,
  name TEXT NOT NULL,
  listen_port INTEGER NOT NULL,
  target_host TEXT NOT NULL,
  target_port INTEGER NOT NULL,
  protocol TEXT NOT NULL DEFAULT 'tcp',
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL
)`,
		`CREATE TABLE IF NOT EXISTS invite_codes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL UNIQUE,
  plan_id INTEGER NOT NULL DEFAULT 0,
  max_uses INTEGER NOT NULL DEFAULT 1,
  used_count INTEGER NOT NULL DEFAULT 0,
  expire_at INTEGER NOT NULL DEFAULT 0,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL
)`,
		`CREATE TABLE IF NOT EXISTS nginx_configs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  server_id TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT 'default',
  content TEXT NOT NULL DEFAULT '',
  enabled INTEGER NOT NULL DEFAULT 1,
  updated_at INTEGER NOT NULL
)`,
		`CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  actor TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL,
  detail TEXT NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL
)`,
		`ALTER TABLE servers ADD COLUMN domain TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE servers ADD COLUMN remark TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE servers ADD COLUMN tags TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE servers ADD COLUMN speed_up INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE servers ADD COLUMN speed_down INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE users ADD COLUMN short_code TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE users ADD COLUMN invite_code TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE inbounds ADD COLUMN share_name TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE inbounds ADD COLUMN tags TEXT NOT NULL DEFAULT ''`,
	}
}
